Repository rcardin/assertj-arrow-core, pull requests merged in 2023-10, with the labels that each got.

#15 Add satisfying fun
  src/main/kotlin/in/rcard/assertj/arrowcore/AbstractEitherAssert.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/AbstractOptionAssert.kt
  src/test/kotlin/in/rcard/assertj/arrowcore/EitherAssert_hasLeftValueSatisfying_Test.kt
  src/test/kotlin/in/rcard/assertj/arrowcore/EitherAssert_hasRightValueSatisfying_Test.kt
  src/test/kotlin/in/rcard/assertj/arrowcore/OptionAssert_hasValueSatisfying_Test.kt
Labels: enhancement, good first issue

#25 Fixed constructors scope
  src/main/kotlin/in/rcard/assertj/arrowcore/AbstractEitherAssert.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/AbstractOptionAssert.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/AbstractRaiseAssert.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/EitherAssert.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/OptionAssert.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/errors/EitherShouldBeLeft.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/errors/EitherShouldBeRight.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/errors/EitherShouldContain.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/errors/EitherShouldContainInstanceOf.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/errors/OptionShouldBeEmpty.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/errors/OptionShouldBePresent.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/errors/OptionShouldContain.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/errors/OptionShouldContainInstanceOf.kt
Labels: bug

#26 Unit tests are not running
  pom.xml
Labels: bug

#27 Fixed the usage of deprecated methods
  src/main/kotlin/in/rcard/assertj/arrowcore/AbstractOptionAssert.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/errors/OptionShouldBeEmpty.kt
  src/main/kotlin/in/rcard/assertj/arrowcore/errors/OptionShouldBePresent.kt
Labels: bug

#28 Added get() method to OptionAssert
  src/main/kotlin/in/rcard/assertj/arrowcore/AbstractOptionAssert.kt
  src/test/kotlin/in/rcard/assertj/arrowcore/OptionAssert_get_Test.kt
Labels: enhancement

#29 Added `asRight()` and `asLeft()` methods to `EitherAssert`
  src/main/kotlin/in/rcard/assertj/arrowcore/AbstractEitherAssert.kt
  src/test/kotlin/in/rcard/assertj/arrowcore/EitherAssert_asLeft_Test.kt
  src/test/kotlin/in/rcard/assertj/arrowcore/EitherAssert_asRight_Test.kt
Labels: enhancement
